# Generated by Django 5.2.5 on 2025-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=10)),
                ('clase', models.TextField(choices=[('Clase alta', 'Clase alta'), ('clase media', 'clase media'), ('clase baja', 'clase baja')], default='clase baja')),
            ],
        ),
    ]
